### ISSUE TITLE
Target Orleans 2.0 and .Net Core 2.0 [meta-ticket]

### ISSUE THREAD

**Issue by pkese** [OrleansContrib/Orleankka#135]
Here we're tracking things that need to be put in place in order to target Orleans 2.0 and .Net Core 2.0:
(based on https://gitter.im/OrleansContrib/Orleankka?at=59e212165c40c1ba799d7fbc )

- [x] match changes in Orleans project structure where necessary https://github.com/dotnet/orleans/issues/3353
- [x] convert `.csproj`/`.fsproj` project files to the new dotnet format
- [x] reinvent build automation as `Nake` won't support .Net Core (`Fake` is a candidate)

**Comment by yevhen** [comment]
All done. It is possible to build Orleankka binaries on Linux, but correct packages can be produced only on Windows at the moment. We can fix this in a separate issue.

**Comment by dfcarpenter** [comment]
Sorry, beginner here. Am I to understand that I can't run this on OSX using .Net 2.0? I'm trying to run the example in the FSharp intro docs and running into several issues on build.

**Comment by yevhen** [comment]
@dfcarpenter are you trying to build from source?

**Comment by dfcarpenter** [comment]
No. I just created a project using `dotnet new classlib -lang F#`
and tried to add packages through Nuget. Anyways, i'm assuming I need to clone the project and build it. I'll try that.

**Comment by yevhen** [comment]
Nope. For F# project you need to reference Orleankka.FSharp package for client, and Orleankka.FSharp.Runtime for server
